version: '3'
services:
  app:
    build: .
    image: thereallactose/backend
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    build: .
    image: thereallactose/frontend 
    ports:
      - "5173:5173"
  db:
    build: .
    image: thereallactose/postgres
    restart: always
    volumes:
     - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
volumes:
  pgdata: