# Use a imagem base do OpenJDK 11
FROM openjdk:11

# Copie o arquivo JAR do aplicativo para a imagem Docker
COPY target/backend-0.0.1-SNAPSHOT.jar /backend-0.0.1-SNAPSHOT.jar

# Define o comando a ser executado quando o contêiner for iniciado
CMD ["java", "-jar", "/backend-0.0.1-SNAPSHOT.jar"]