# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

defaults:
      run:
        working-directory: ./frontend

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend # Define o diret贸rio de trabalho para o job "test"

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        working-directory: ./frontend # Defina o diret贸rio de trabalho para esta etapa
    - run: npm ci
    - run: npm test

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend # Define o diret贸rio de trabalho para o job "build"

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        working-directory: ./frontend # Defina o diret贸rio de trabalho para esta etapa
    - run: npm ci
    - run: npm run build --if-present
